### ISSUE TITLE
demo is not working

### ISSUE THREAD

**Issue by zghwi** [tsanak/Trello-clone#1]
hi
when i go to the demo it returns: `Not found - Request ID: 35d730e2-0a93-4fab-b2b2-0724c4e7beb8-11850131`

here is the image:
![image](https://user-images.githubusercontent.com/73612690/102789507-eb891e80-43ac-11eb-8f47-ab96b9a0f9e8.png)

**Comment by tsanak** [comment]
Hey, thanks for letting me know!
I have updated the link, you can view the demo in [https://eager-joliot-16d198.netlify.app](url).

**Comment by zghwi** [comment]
No problem, and thanks!

**Comment by zghwi** [comment]
nice job!
